name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted
   
    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: sudo docker build -t multi-stage .
    - name: docker run container 
      run: sudo docker run -d --name multi-container -p 8080:8080 multi-stage
    - name: docker container information 
      run: docker container ps  
    - name: Run tests inside the container
      run: sudo docker exec multi-container curl -I https://google.com

